---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.1.100 kube-master
        - 172.16.1.101 kube-node1
        - 172.16.1.102 kube-node2
        - 172.16.1.103 registry

    - name: Clona reposit贸rio com os arquivos do curso para a HOME do usuario suporte
      git:
        repo: 'https://github.com/4linux/4541.git'
        dest: /home/suporte/4541
        
    - name: Cria o diret贸rio .ssh
      file:
        path: /home/suporte/.ssh
        state: directory
        owner: suporte
        group: suporte
        mode: '0755'
        
    - name: Cria o diret贸rio data
      file:
        path: /home/suporte/data
        state: directory
        owner: suporte
        group: suporte
        mode: '0755'

    - name: Criando o arquivo authorized_keys
      copy:
        src: files/authorized_keys
        dest: /home/suporte/.ssh/authorized_keys
        owner: suporte
        group: suporte
        mode: 0644
   
    - name: Adiciona o usuario suporte no grupo docker
      user:
        name: suporte
        group: docker

    - name: Cria o diret贸rio registry:5000
      file:
        path: /etc/docker/certs.d/registry:5000
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Criando o arquivo ca.crt
      copy:
        src: files/ca.crt
        dest: /etc/docker/certs.d/registry:5000
        owner: suporte
        group: suporte
        mode: '0644'
        
    - name: Criando o arquivo daemon.json
      copy:
        src: files/daemon.json
        dest: /etc/docker/
        owner: root
        group: root
        mode: '0644'
   
    - name: Remove swap do arquivo /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Desativa o swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Instala os pacotes do Kubernetes
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - kubelet=1.21.1-00
        - kubeadm=1.21.1-00
        - kubectl=1.21.1-00

    - name: Reinicia o kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

    - name: Copia o arquivo join-command.sh
      copy: src=join-command dest=/tmp/join-command.sh mode=0777

    - name: Adiciona o node no cluster
      command: sh /tmp/join-command.sh
