apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
