---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
data:
  DB_PASS: NGxpbnV4
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItcmVnaXN0cnk6NTAwMCI6eyJ1c2VybmFtZSI6ImFuYWxpc3RhIiwicGFzc3dvcmQiOiI0bGludXgiLCJhdXRoIjoiWVc1aGJHbHpkR0U2Tkd4cGJuVjQifX19



