---
apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: frontend-blue
spec:  
  template:  
    spec:  
      containers:  
      - name: 4linux-php
        image: docker-registry:5000/4linux-php:v1
