---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-imutavel
  name: pod-imutavel
spec:
  containers:
  - image: httpd
    name: pod-imutavel
    startupProbe:
      exec:
        command:
        - rm
        - /bin/bash
      initialDelaySeconds: 1
      periodSeconds: 5
