---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: volume-claim-local
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
