---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits1
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: 0.5
    defaultRequest:
      memory: 100Mi
      cpu: 0.2
    type: Container
