---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600"
    resources:
      limits:
        memory: "300Mi"
        cpu: 0.8
  nodeSelector:
    cloud: AWS
