---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-client
spec:
  serviceAccountName: operator
  containers:
    - name: kubectl-container
      image: lachlanevenson/k8s-kubectl:v1.19.1
      command: ["sleep", "86400"]
