---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frontend-claim-nfs
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
