---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nfs-app
  namespace: 4labs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10G
