---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: devops
  name: app-v1
  namespace: 4labs
spec:
  replicas: 1
  selector:
    matchLabels:
      team: devops
  strategy: {}
  template:
    metadata:
      labels:
        team: devops
    spec:
      containers:
      - image: registry:5000/4linux-app:v1
        name: app-v1
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-configmaps
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-configmaps
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-configmaps
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-configmaps
              key: DB_NAME
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASS
        volumeMounts:
        - name: claim-nfs-app
          mountPath: "/app"
        - name: config-volume-php
          mountPath: "/php-ini/"
      volumes:
        - name: claim-nfs-app
          persistentVolumeClaim:
            claimName: claim-nfs-app
        - name: config-volume-php
          configMap:
            name: php-config  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: devops
  name: app-v2
  namespace: 4labs
spec:
  replicas: 1
  selector:
    matchLabels:
      team: devops
  strategy: {}
  template:
    metadata:
      labels:
        team: devops
    spec:
      containers:
      - image: registry:5000/4linux-app:v2
        name: app-v2
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-configmaps
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-configmaps
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-configmaps
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-configmaps
              key: DB_NAME
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASS
        volumeMounts:
        - name: claim-nfs-app
          mountPath: "/app"
        - name: config-volume-php
          mountPath: "/php-ini/"
      volumes:
        - name: claim-nfs-app
          persistentVolumeClaim:
            claimName: claim-nfs-app
        - name: config-volume-php
          configMap:
            name: php-config  
