---
- name: kube-master
  box: trombik/ansible-ubuntu-18.04-amd64
  hostname: kube-master
  ipaddress: 172.16.1.100
  memory: 3584
  cpus: 2
  provision: provision/ansible/kube-master.yaml

- name: kube-node1
  box: trombik/ansible-ubuntu-18.04-amd64
  hostname: kube-node1
  ipaddress: 172.16.1.101
  memory: 1536
  cpus: 2
  provision: provision/ansible/kube-node1.yaml

- name: kube-node2
  box: trombik/ansible-ubuntu-18.04-amd64
  hostname: kube-node2
  ipaddress: 172.16.1.102
  memory: 1536
  cpus: 2
  provision: provision/ansible/kube-node2.yaml

- name: kube-registry
  box: trombik/ansible-ubuntu-18.04-amd64
  hostname: registry
  ipaddress: 172.16.1.103
  memory: 512
  cpus: 1
  provision: provision/ansible/kube-registry.yaml
