apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "RequestReceived"

rules:

  - level: None
    verbs: ["get", "list", "watch"]

  - level: Metadata
    resources:
    - group: ""
      resources: ["secrets"]
