---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-hostpath
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: site
      mountPath: /usr/share/nginx/html
  volumes:
  - name: site
    hostPath:
      path: /tmp/site
      type: DirectoryOrCreate
