---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  schedulerName: 4labs-scheduler
  containers:
  - name: busybox
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "3600"
