---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-limits
  namespace: 4labs-limits
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 1Gi
