---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmaps
  namespace: 4labs
data:
  DB_HOST: mysql
  DB_NAME: php
  DB_PORT: "3306"
  DB_USER: php
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmaps
  namespace: 4labs
data:
  MYSQL_DATABASE: php
  MYSQL_USER: php
