---
apiVersion: v1  
kind: Secret  
metadata:  
  name: mysql-secrets
type: Opaque  
data:  
  mysql-root-password: NGxpbnV4
  mysql-user: c3Vwb3J0ZQ==
  mysql-password: NGxpbnV4
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    imagePullPolicy: IfNotPresent
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: mysql-root-password
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: mysql-user
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: mysql-password
    readinessProbe:
      exec:
        command: ["mysql", "-h", "127.0.0.1", "-p$MYSQL_ROOT_PASSWORD", "-e", "SELECT 1"]
      initialDelaySeconds: 30
      periodSeconds: 2
      timeoutSeconds: 1
