---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: 4labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: registry:5000/4linux-app:latest
        name: frontend
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: frontend-configmaps
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: frontend-configmaps
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: frontend-configmaps
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: frontend-configmaps
              key: DB_NAME
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: DB_PASS

        volumeMounts:
        - name: claim-nfs-frontend
          mountPath: "/app"
        - name: config-volume-php
          mountPath: "/app/php-ini/"

      volumes:
        - name: claim-nfs-frontend
          persistentVolumeClaim:
            claimName: claim-nfs-frontend
        - name: config-volume-php
          configMap:
            name: php-config
      nodeName: kube-node2            
