---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.1.100 kube-single-master
        - 172.16.1.101 kube-single-node1
        - 172.16.1.102 kube-single-node2

    - name: Instalando pacotes de dependencias para o curso de Kubernetes
      yum:
        name: ['git']

    - name: Cria o diretório .ssh
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Criando o arquivo authorized_keys
      copy:
        src: files/authorized_keys
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: 0644
        
    - name: Clona repositório com os arquivos do curso para a HOME do usuario suporte
      git:
        repo: 'https://github.com/4linux/4541.git'
        dest: /home/suporte/4541

    - name: Clona repositório com os arquivos do curso para a HOME do usuario root
      git:
        repo: 'https://github.com/4linux/4541.git'
        dest: /root/4541
