apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-seccomp
  name: pod-seccomp
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: jess/amicontained
    name: pod-seccomp
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "amicontained" ]
    securityContext:
      allowPrivilegeEscalation: false    
  nodeName: kube-node2
