---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-simples
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'echo Hello from the Kubernetes job! && sleep 30']
      restartPolicy: Never
