---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-paralelo
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: parallel
        image: busybox
        command: ['sh', '-c', 'echo Started on $(hostname) && sleep 20']
      restartPolicy: Never
