---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-bloco
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: site-volume
  volumes:
  - name: site-volume
    persistentVolumeClaim:
      claimName: pvc-longhorn
