---
apiVersion: v1
kind: Pod
metadata:
  name: server-pod
  labels:
    app: server
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
spec:
  containers:
  - name: busybox-container
    image: busybox
    command:
    - "sh"
    - "-c"
    - "sleep 3000"
