---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ops
  name: pod1
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
      - containerPort: 80
  - image: registry:2
    name: registry
    ports:
      - containerPort: 5000
