---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-nfs-app
  namespace: 4labs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 200.100.50.200
    path: /opt/app
