---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-objects
spec:
  hard:
    pods: "15"
    services: "5"
    secrets: "5"
    configmaps: "10"
    replicationcontrollers: "1"
    persistentvolumeclaims: "5"
    services.loadbalancers: "2"
    services.nodeports: "0"
