---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rewrite   
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 4labs.example
    http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
      - path: /apache
        pathType: Prefix
        backend:
          service:
            name: apache
            port:
              number: 80
