---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: analista-csr
spec:
  groups:
  - system:authenticated
  request: REQUEST
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
