apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-secrets
  name: deploy-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-secrets
  template:
    metadata:
      labels:
        app: deploy-secrets
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
