---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: green
  name: frontend-green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - image: docker-registry:5000/4linux-php:v2
        imagePullPolicy: IfNotPresent
        name: 4linux-php
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: frontend-configmaps
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: frontend-configmaps
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: frontend-configmaps
              key: DB_USER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: frontend-configmaps
              key: DB_NAME
        - name: PHP_INI
          valueFrom:
            configMapKeyRef:
              name: frontend-configmaps
              key: PHP_INI
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: DB_PASS
        volumeMounts:
        - name: frontend-claim-nfs
          mountPath: "/app"
        - name: config-volume-php
          mountPath: "/app/php-ini/"
      initContainers:
      - image: alpine/git:2.40.1
        imagePullPolicy: IfNotPresent
        name: git
        command: ['sh', '-c', 'if [ ! -d "/app/green" ]; then cd /app && rm -rf ..?* .[!.]* * && git clone --branch green https://github.com/4linux/4linux-php.git /app; fi']
        volumeMounts:
        - name: frontend-claim-nfs
          mountPath: /app
      volumes:
        - name: config-volume-php
          configMap:
            name: php-config
        - name: frontend-claim-nfs
          persistentVolumeClaim:
            claimName: frontend-claim-nfs
      imagePullSecrets:
      - name: regcred
