---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: infra
spec:
  addresses:
  - 172.16.1.201-172.16.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
