---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-static
  labels:
    static: pod
spec:
  containers:
    - name: httpd
      image: httpd
      imagePullPolicy: IfNotPresent
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
