apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    imagePullPolicy: IfNotPresent
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: mysql-root-password
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: mysql-user
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: mysql-password
