---
apiVersion: v1
kind: Pod
metadata:
  name: pod-user-group-context
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
  containers:
  - name: pod-user-group-context
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sleep", "999999"]
