---
apiVersion: v1
kind: Pod
metadata:
  name: pod-group-context
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: backup
    emptyDir: {}
  containers:
  - name: pod-group-context
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sleep", "999999"]
    volumeMounts:
    - name: backup
      mountPath: /backup/servers
    securityContext:
      allowPrivilegeEscalation: false
