---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-nfs-mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.16.1.103
    path: /opt/data
