---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-nfs-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.16.1.103
    path: /opt/app

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nfs-app
  namespace: 4labs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
