---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-nfs-mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.16.1.103
    path: /opt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-nfs-mysql
  namespace: 4labs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
